---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=old-test-loader
  - EMBER_TRY_SCENARIO=npm-test-loader
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: jYS1ZMOn+54LctBnRGLM4JccV5UrWw5X2N+u+8PcYXLwlfO1ajhCuXMCO41qzix3qDi6GSv/hisVyZAaYz6D9wj0iRfp7lpOQlfBcm5Nnkko+L43ftXEdecseZMYptMZaUf48ynV7xsvJ4AILSzLJCM3aazr6WOkknVGCEN0Y1c=
  on:
    tags: true
    repo: ember-cli/ember-cli-qunit
